version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: ofurhetju_db
    environment:
      POSTGRES_DB: ofurhetjudb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: